package utils.messageRelated;

public enum NotificationOpcode {
        STORE_REVIEW(101), PRODUCT_REVIEW(102), PURCHASE_IN_STORE(103), QUESTION(104), CLOSE_STORE_PERMANENTLY(105), OPEN_STORE(106), CLOSE_STORE(107),
        APPOINT_MANAGER(111), APPOINT_OWNER(112), FIRE_MANAGER(113), FIRE_OWNER(114),
        ADD_MANGER_PERMISSTION(121), REMOVE_MANGER_PERMISSTION(122),
        COMPLAINT(1), CHAT_MESSAGE(3),
        REVIEW_FEEDBACK(13);

        NotificationOpcode(int i) {
        }
}
